### ISSUE TITLE
Move NER labels from Tag nodes to TagOccurrence nodes

### ISSUE THREAD

**Issue by vlasta-kus** [graphaware/neo4j-nlp#105] opened 2018-07-23 11:52 UTC
Named Entities might depends on the context. The same word(s) might have a different meaning in different texts.
Also, no NER is 100% accurate. It therefore happens that due to handful mis-identifications all other occurrences of that Tag are currently labeled as a named entity.

Example: custom named entity MUSICAL_INSTRUMENT
```
MATCH (a:AnnotatedText)-->(:Sentence)-[:HAS_TAG]->(t:NER_Musical_instrument) RETURN t.value, count(distinct a) as n_docs order by n_docs desc limit 10

t.value | n_docs
----------------
"star" | 7571
"piano" | 1895
"violin" | 992
"block" | 756
"organ" | 589
"helium" | 497
"guitar" | 485
"cello" | 469
"cells" | 420
"flute" | 374
```

Notice the word "star" - it appears as NE in all 7571 documents. Now looking at TagOccurrence nodes only, we can see that it was actually mis-identified as a musical instrument only in 6 documents!
```
MATCH (a:AnnotatedText)-->(:Sentence)-[:SENTENCE_TAG_OCCURRENCE]->(to:TagOccurrence)-[:TAG_OCCURRENCE_TAG]->(t:Tag) WHERE "MUSICAL_INSTRUMENT" in to.ne RETURN t.value, count(distinct a) as n_docs order by n_docs desc limit 10


t.value | n_docs
----------------
"piano" | 1767
"violin" | 889
"organ" | 558
"cells" | 421
"cello" | 398
"block" | 344
"violins" | 315
"guitar" | 306
"flute" | 292
"horn" | 255
...
"star" | 6
```

**Comment by ikwattro** [comment] 2018-07-23 13:36
Duplicate of #95

**Closed by ikwattro** 2018-07-23 13:36 UTC
